// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderFlow.Infrastructure.Data;

#nullable disable

namespace OrderFlow.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526131249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderFlow.Domain.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("symbol");

                    b.HasKey("Code")
                        .HasName("pk_currency");

                    b.ToTable("currency", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "BRL",
                            Name = "Real Brasileiro",
                            Symbol = "R$"
                        },
                        new
                        {
                            Code = "USD",
                            Name = "United States Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Code = "EUR",
                            Name = "Euro",
                            Symbol = "€"
                        });
                });

            modelBuilder.Entity("OrderFlow.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("available_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.ToTable("product", null, t =>
                        {
                            t.HasCheckConstraint("chk_product_price_positive", "unit_price >= 0");

                            t.HasCheckConstraint("chk_product_stock_positive", "available_quantity >= 0");
                        });
                });

            modelBuilder.Entity("OrderFlow.Domain.Entities.SalesOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<int>("SalesOrderStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("sales_order_status_id");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_sales_order");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_sales_order_currency_code");

                    b.HasIndex("SalesOrderStatusId")
                        .HasDatabaseName("ix_sales_order_sales_order_status_id");

                    b.ToTable("sales_order", null, t =>
                        {
                            t.HasCheckConstraint("chk_sales_order_total_positive", "total >= 0");
                        });
                });

            modelBuilder.Entity("OrderFlow.Domain.Entities.SalesOrderItem", b =>
                {
                    b.Property<long>("SalesOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sales_order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("SalesOrderId", "ProductId")
                        .HasName("pk_sales_order_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sales_order_items_product_id");

                    b.ToTable("sales_order_items", null, t =>
                        {
                            t.HasCheckConstraint("chk_price_positive", "unit_price >= 0");

                            t.HasCheckConstraint("chk_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("OrderFlow.Domain.Entities.SalesOrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sales_order_status");

                    b.ToTable("sales_order_status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pedido de venda recebido pelo sistema e aguardando processamento.",
                            Name = "Placed"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pagamento aprovado e pedido de venda confirmado.",
                            Name = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pedido de venda cancelado.",
                            Name = "Canceled"
                        });
                });

            modelBuilder.Entity("OrderFlow.Domain.Entities.SalesOrder", b =>
                {
                    b.HasOne("OrderFlow.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_order_currency_currency_code");

                    b.HasOne("OrderFlow.Domain.Entities.SalesOrderStatus", "SalesOrderStatus")
                        .WithMany()
                        .HasForeignKey("SalesOrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_order_sales_order_status_sales_order_status_id");

                    b.Navigation("Currency");

                    b.Navigation("SalesOrderStatus");
                });

            modelBuilder.Entity("OrderFlow.Domain.Entities.SalesOrderItem", b =>
                {
                    b.HasOne("OrderFlow.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_order_items_products_product_id");

                    b.HasOne("OrderFlow.Domain.Entities.SalesOrder", "SalesOrder")
                        .WithMany("Items")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_order_items_sales_orders_sales_order_id");

                    b.Navigation("Product");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("OrderFlow.Domain.Entities.SalesOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
